
package com.bobsystem.ws.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWsExample", targetNamespace = "http://webservice.ws.bobsystem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWsExample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArray", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetArray")
    @ResponseWrapper(localName = "getArrayResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetArrayResponse")
    public List<String> getArray(
        @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetStringResponse")
    public String getString();

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrimitiveTypes", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetPrimitiveTypes")
    @ResponseWrapper(localName = "getPrimitiveTypesResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetPrimitiveTypesResponse")
    public double getPrimitiveTypes();

    /**
     * 
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWrappingTypes", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetWrappingTypes")
    @ResponseWrapper(localName = "getWrappingTypesResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetWrappingTypesResponse")
    public Double getWrappingTypes();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetListResponse")
    public List<Object> getList();

    /**
     * 
     * @return
     *     returns com.bobsystem.ws.wsimport.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompsiteType", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetCompsiteType")
    @ResponseWrapper(localName = "getCompsiteTypeResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.GetCompsiteTypeResponse")
    public Student getCompsiteType();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "passCompsiteType", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.PassCompsiteType")
    @ResponseWrapper(localName = "passCompsiteTypeResponse", targetNamespace = "http://webservice.ws.bobsystem.com/", className = "com.bobsystem.ws.wsimport.PassCompsiteTypeResponse")
    public void passCompsiteType(
        @WebParam(name = "arg0", targetNamespace = "")
            Student arg0);

}
