
package com.bobsystem.ws.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsExampleService", targetNamespace = "http://webservice.ws.bobsystem.com/", wsdlLocation = "http://localhost:8080/service/ws-test?wsdl")
public class WsExampleService
    extends Service
{

    private final static URL WSEXAMPLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WsExampleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WsExampleService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/service/ws-test?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/service/ws-test?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSEXAMPLESERVICE_WSDL_LOCATION = url;
    }

    public WsExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsExampleService() {
        super(WSEXAMPLESERVICE_WSDL_LOCATION, new QName("http://webservice.ws.bobsystem.com/", "WsExampleService"));
    }

    /**
     * 
     * @return
     *     returns IWsExample
     */
    @WebEndpoint(name = "WsExamplePort")
    public IWsExample getWsExamplePort() {
        return super.getPort(new QName("http://webservice.ws.bobsystem.com/", "WsExamplePort"), IWsExample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsExample
     */
    @WebEndpoint(name = "WsExamplePort")
    public IWsExample getWsExamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ws.bobsystem.com/", "WsExamplePort"), IWsExample.class, features);
    }

}
